language: python
python:
  - "3.7"
install:
  - pip install -r requirement.txt
env:
  global:
  - USER="LyuLumos"
  - EMAIL="3208413453@qq.com"
  - REPO="VJudge-Spider-on-TravisCI"
  - FILES="out.csv"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  # - secure: "put travis gem output here => http://docs.travis-ci.com/user/encryption-keys/"
services:
  - xvfb
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - sleep 3 
script:
  - python run.py
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f ${FILES} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${M8rl4_zMNTHjaF1M331pHg}@${GH_REPO}" master > /dev/null 2>&1
branches:
  only:
    - main