language: python
python:
  - "3.7"
install:
  - sudo apt-get update
  - sudo apt-get install libgconf2-4 libxss1 unzip -y
  - sudo apt-get -f install -y
  - pip install -r requirement.txt
env:
  global:
  - USER="CUCCS"
  - REPO="VJudge-Spider-on-TravisCI"
  - FILES="out.csv"
  - GH_REPO="github.com/${USER}/${REPO}.git"
before_script:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
  - LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - sudo mv chromedriver /usr/bin/
  - chromedriver --version
script:
  - python run.py
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone --branch=$TRAVIS_BRANCH https://${GH_REPO}
  # - git checkout -b data
  # - git branch
  - cd ${REPO}
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${USER}/${REPO}.git > /dev/null 2>&1
  - mv -f ../${FILES} ${FILES}
  - ls -al
  - git add .
  - git commit -m "[skip travis] ${MESSAGE}; Build by Travis CI"
  - git push --force --quiet origin  $TRAVIS_BRANCH
branches:
  only:
    - main
    - dev
notifications:
  email: false
