language: python
python:
  - "3.7"
install:
  - sudo apt-get update
  - sudo apt-get install libgconf2-4 libxss1 unzip -y
  - sudo apt-get -f install -y
  - pip install -r requirement.txt
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
env:
  global:
  - USER="LyuLumos"
  - EMAIL="3208413453@qq.com"
  - REPO="VJudge-Spider-on-TravisCI"
  - FILES="out.csv"
  - GH_REPO="github.com/${USER}/${REPO}.git"
before_script:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
  - LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - sudo mv chromedriver /usr/bin/
  - chromedriver --version
  - git clone --branch=out https://${GH_REPO}
script:
  - python run.py
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  # - git branch
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
    # - mv -f ../${FILES} ${FILES}
  - cd REPO
  - ls  -al
  - git add .
  - git commit -m "${MESSAGE}; Build by Travis CI"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REPO}" out

branches:
  only:
    - data
    - z1933dev
